# -*- coding: utf-8 -*-
"""divisors.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1627CfMQ_vIOPhfmnE49v8krQ49XGGkj_
"""

import sys

number = int(sys.argv[1])

for i in range(1,number+1):
  if number % i == 0:
    print(i,end = " ")
print()